Create VES client example for domain 'stateChange'
Python script and json template added.
READMEpy.md updated.
In addtion also the ves-test-collecotor updated to latest schema.

The script results in:

  demx8as6 @ martindev ~/workspace/o-ran-sc/oam/solution/dev/ves-test-collector/client-scripts-ves-v7 (OAM-184)
  └─ $ ▶ python3 sendVesStateChange.py --pnf nSky
  ################################################################################
  # send VES stateChange
  /usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request
   is being made to host 'localhost'. Adding certificate verification is strongly advised. See:
  https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    warnings.warn(
  <Response [202]>

This is expected.

Due to an issue in the configuration of DMaaP it results
at VES colllector in:

  com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException:
  DMaaP configuration contains no configuration for domain: 'ves-statechange'

This is a new issue reported ot DMaaP project and not in scope of OAM-184,

IssueID: OAM-184
Change-Id: I6cd7a92ccf00b0f8621d6bb7312bb054fc69a916
Signed-off-by: demx8as6 <martin.skorupski@highstreet-technologies.com>